id: AA203524D
title: Liberation Through Training in the Realm of Amitābha, Boundless Light
type: translation
pechas:
- I4E5300D9
- I0D69B40A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:50.235720
  last_modified_at: 2023-01-04 11:33:50.235728
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I4E5300D9/FB0F: '8386'
  I0D69B40A/C6E0: '8386'
